import { BadgeCheck, CalendarCheck, FileDown, Mail, Sparkles } from "lucide-react";
import { Badge } from "@/components/ui/badge";

function ScoreRing({ value }: { value: number }) {
  const r = 34;
  const c = 2 * Math.PI * r;
  return (
    <svg viewBox="0 0 84 84" className="size-[84px] -rotate-90" aria-hidden>
      <circle cx="42" cy="42" r={r} fill="none" stroke="#e2e8f0" strokeWidth="9" />
      <circle
        cx="42"
        cy="42"
        r={r}
        fill="none"
        stroke="#16a34a"
        strokeWidth="9"
        strokeLinecap="round"
        strokeDasharray={c}
        strokeDashoffset={c * (1 - value / 100)}
      />
    </svg>
  );
}

const BARS = [
  { label: "Leadership & Vision", pct: 82, color: "#16a34a" },
  { label: "Teaching Quality", pct: 58, color: "#d97706" },
  { label: "Finance", pct: 64, color: "#d97706" },
  { label: "Safety & Child Protection", pct: 91, color: "#059669" },
];

export function ReportPreview() {
  return (
    <div className="relative mx-auto w-full max-w-md lg:max-w-none">
      {/* Main report card */}
      <div className="relative rounded-[28px] border border-slate-200/80 bg-white p-6 shadow-lift sm:p-7">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2.5">
            <span className="grid size-8 place-items-center rounded-lg bg-brand-700">
              <Sparkles className="size-4 text-white" />
            </span>
            <div className="leading-none">
              <p className="text-[13px] font-bold text-slate-900">School Health Report</p>
              <p className="mt-1 text-[11px] text-slate-400">Generated by KAEC AI</p>
            </div>
          </div>
          <Badge variant="soft">Sample</Badge>
        </div>

        <div className="mt-6 flex items-center gap-5">
          <div className="relative grid place-items-center">
            <ScoreRing value={74} />
            <div className="absolute text-center">
              <span className="block text-2xl font-extrabold text-slate-900">74</span>
              <span className="block text-[10px] font-semibold uppercase tracking-wide text-slate-400">overall</span>
            </div>
          </div>
          <div className="space-y-2">
            <Badge variant="green">Health rating · Healthy</Badge>
            <p className="text-xs leading-relaxed text-slate-500">
              Priority area: <span className="font-semibold text-slate-700">Teaching Quality</span>
            </p>
            <p className="text-xs leading-relaxed text-slate-500">
              4 quick wins · 9 recommendations · 90-day plan
            </p>
          </div>
        </div>

        <div className="mt-6 space-y-3.5">
          {BARS.map((b) => (
            <div key={b.label}>
              <div className="mb-1.5 flex items-center justify-between text-[11px]">
                <span className="font-medium text-slate-600">{b.label}</span>
                <span className="font-bold" style={{ color: b.color }}>{b.pct}%</span>
              </div>
              <div className="h-2 overflow-hidden rounded-full bg-slate-100">
                <div className="h-full rounded-full" style={{ width: `${b.pct}%`, background: b.color }} />
              </div>
            </div>
          ))}
          <p className="text-right text-[10px] font-medium text-slate-400">+ 7 more departments</p>
        </div>

        <div className="mt-5 flex flex-wrap gap-2 border-t border-slate-100 pt-5">
          <span className="inline-flex items-center gap-1.5 rounded-full bg-slate-50 px-3 py-1.5 text-[11px] font-semibold text-slate-600">
            <FileDown className="size-3.5 text-brand-600" /> PDF report
          </span>
          <span className="inline-flex items-center gap-1.5 rounded-full bg-slate-50 px-3 py-1.5 text-[11px] font-semibold text-slate-600">
            <Mail className="size-3.5 text-brand-600" /> Emailed to you
          </span>
          <span className="inline-flex items-center gap-1.5 rounded-full bg-slate-50 px-3 py-1.5 text-[11px] font-semibold text-slate-600">
            <BadgeCheck className="size-3.5 text-brand-600" /> AI Coach chat
          </span>
        </div>
      </div>

      {/* Floating card: quick wins */}
      <div className="absolute -right-3 -top-8 hidden animate-float rounded-2xl border border-slate-200/80 bg-white/95 px-4 py-3 shadow-lift backdrop-blur sm:block">
        <div className="flex items-center gap-2.5">
          <span className="grid size-8 place-items-center rounded-full bg-mint-50">
            <Sparkles className="size-4 text-mint-600" />
          </span>
          <div className="leading-tight">
            <p className="text-xs font-bold text-slate-900">4 quick wins found</p>
            <p className="text-[10px] text-slate-400">start this week, zero cost</p>
          </div>
        </div>
      </div>

      {/* Floating card: 90-day plan */}
      <div
        className="absolute -bottom-8 -left-3 hidden animate-float rounded-2xl border border-slate-200/80 bg-white/95 px-4 py-3 shadow-lift backdrop-blur sm:block"
        style={{ animationDelay: "1.2s" }}
      >
        <div className="flex items-center gap-2.5">
          <span className="grid size-8 place-items-center rounded-full bg-brand-50">
            <CalendarCheck className="size-4 text-brand-600" />
          </span>
          <div>
            <p className="text-xs font-bold text-slate-900">90-day plan ready</p>
            <div className="mt-1.5 flex gap-1">
              {["30", "60", "90"].map((d) => (
                <span key={d} className="rounded-md bg-brand-50 px-1.5 py-0.5 text-[10px] font-bold text-brand-700">
                  Day {d}
                </span>
              ))}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
