import type { Metadata } from "next";
import { ShieldCheck } from "lucide-react";
import { Header } from "@/components/site/Header";
import { Footer } from "@/components/site/Footer";
import { Card } from "@/components/ui/card";
import { SITE } from "@/lib/site";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: "How KAEC School Health Check collects, uses and protects your information.",
};

const SECTIONS = [
  {
    title: "What we collect",
    body: [
      "When you run a School Health Check we collect the school profile you type in: school name, your name, email, optional phone number, country, state/region, school type, level and population ranges. We then store the answers you give to the 55 assessment indicators, and the report that is generated from them.",
      "If you contact us, we store your name, email, phone, school name and message so we can respond.",
      "We do not create accounts, we do not use passwords, and we do not collect student data of any kind.",
    ],
  },
  {
    title: "How we use it",
    body: [
      "Your school profile and answers are used for exactly three things: generating your AI health report, emailing that report to you, and letting you resume an unfinished assessment.",
      "We compute anonymous, aggregate statistics (for example, average scores by region or school type). These statistics contain no school names, no personal names and no contact details, and cannot reasonably identify any school or individual.",
      "We never sell, rent or trade your information to anyone.",
    ],
  },
  {
    title: "AI processing",
    body: [
      "Reports are generated by artificial intelligence. Where an AI provider is configured (OpenAI), your school's assessment responses are sent to that provider solely to produce your report text, under the provider's own data-processing terms. We do not use your school's data to train AI models.",
      "The AI Coach feature answers questions using only the contents of your own report as context.",
    ],
  },
  {
    title: "Data retention & your choices",
    body: [
      "Reports remain accessible at their unique, unguessable link so you can return to them, download the PDF, or resend the email. You may request deletion of your school's record at any time by emailing us — we will remove the school profile, answers, report and contact history.",
      "Assessment autosaves are stored both on our servers and locally in your own browser, so you can resume. Clearing your browser storage removes the local copy.",
    ],
  },
  {
    title: "Security",
    body: [
      "Data is transmitted over encrypted connections and stored in a secured database with strict access controls. No method of transmission or storage is perfectly secure, but we apply industry-standard practices proportionate to the sensitivity of school-profile data.",
    ],
  },
  {
    title: "Contact",
    body: [
      `Questions about this policy or your data? Email ${SITE.email}. We respond to privacy requests within a few working days.`,
    ],
  },
];

export default function PrivacyPage() {
  return (
    <>
      <Header />
      <main className="pt-[68px]">
        <section className="border-b border-slate-100 bg-gradient-to-b from-brand-50/70 to-white">
          <div className="mx-auto max-w-3xl px-4 py-16 text-center sm:px-6">
            <span className="inline-flex items-center gap-2 rounded-full border border-brand-100 bg-white px-4 py-1.5 text-xs font-semibold text-brand-800 shadow-soft">
              <ShieldCheck className="size-3.5" /> Plain-language policy
            </span>
            <h1 className="mt-5 text-4xl font-extrabold tracking-tight text-slate-900 sm:text-5xl">Privacy Policy</h1>
            <p className="mx-auto mt-4 max-w-xl text-base leading-relaxed text-slate-500">
              The short version: your answers generate your report and nothing else. No ads, no data
              sales, no student data — ever.
            </p>
          </div>
        </section>
        <section className="mx-auto max-w-3xl px-4 py-14 sm:px-6">
          <div className="space-y-5">
            {SECTIONS.map((s, i) => (
              <Card key={s.title} className="p-7 sm:p-8">
                <h2 className="flex items-baseline gap-3 text-lg font-bold text-slate-900">
                  <span className="text-sm font-black text-brand-600">{String(i + 1).padStart(2, "0")}</span>
                  {s.title}
                </h2>
                <div className="mt-3 space-y-3">
                  {s.body.map((p, j) => (
                    <p key={j} className="text-sm leading-relaxed text-slate-600">{p}</p>
                  ))}
                </div>
              </Card>
            ))}
          </div>
          <p className="mt-8 text-center text-xs text-slate-400">
            Last updated: {new Date().toLocaleDateString("en-GB", { month: "long", year: "numeric" })} · {SITE.name}
          </p>
        </section>
      </main>
      <Footer />
    </>
  );
}
